name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  DO_NOT_TRACK: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Publish snapshot packages
        if: ${{ github.event_name == 'pull_request' }}
        run: ./node_modules/.bin/pkg-pr-new publish --pnpm ./packages/starlight-theme-nova ./packages/shiki-twoslash-renderer

  screenshot:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: pnpm run test:install

      - name: Build
        run: pnpm run build

      - name: Run screenshot tests
        id: test
        continue-on-error: true
        run: pnpm run test

      - name: Upload Playwright report
        if: steps.test.outcome == 'failure'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-report-${{ matrix.os }}
          path: website/playwright-report/

      - name: Update snapshots if tests failed
        if: steps.test.outcome == 'failure'
        run: pnpm run test:update

      - name: Configure git
        if: steps.test.outcome == 'failure' && github.ref != 'refs/heads/master'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push snapshot changes
        if: steps.test.outcome == 'failure' && github.ref != 'refs/heads/master'
        run: |
          git add --all
          git commit -m "chore: [skip ci] update snapshots"
          git pull --rebase
          git push

      - name: Fail if snapshots changed
        if: steps.test.outcome == 'failure'
        run: exit 1
